version: "3.4"
services:
  dump:
    image: $MY_IMAGE
    volumes: 
      - "./persist:/mnt"
    environment:
      - DB_SERVICE_NAME=mongodb
      - DB_PORT=27017
      - MONGODB_DATABASE=db1
      - MONGODB_USERNAME=user1
      - MONGODB_PASSWORD=password123
      - BACKUP_DIR=mongo
      - MONGODB_CRON_PATTERN=*/3 * * * *
      - BACKUP_TIME=7
      - REMOTE_BACKUP=true
      - REMOTE_HOST=10.107.148.24
      - REMOTE_DIR=/home/ddd  
      - REMOTE_SERVER_PORT=22
      - REMOTE_USER=user
